language: elixir
elixir: "1.6.2"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

before_script:
  - psql -c "CREATE EXTENSION postgis" -U postgres
  - psql -c "CREATE USER airquality WITH CREATEDB PASSWORD 'airquality'; ALTER USER airquality superuser;" -U postgres

script:
  - mix test

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
