language: elixir
elixir:
  - 1.6.2

addons:
  postgresql: '9.6'
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

before_script:
  - psql -c " CREATE USER airquality WITH CREATEDB PASSWORD 'airquality'; ALTER USER airquality superuser;" -U postgres

script:
  - mix test

notifications:
  email: false
